### ISSUE TITLE
Crashed with error... Perhaps out of memory?

### ISSUE THREAD

**Issue by trashken** [giuseppe99barchetta/SuggestArr#14] opened 2024-10-18 07:52 UTC
Not sure why but it errored out with the latest version. 

```
2024-10-18 15:48:44,911 - ContentAutomation - INFO - Processing movie: 41244 (TMDB id)
2024-10-18 15:48:45,236 - ContentAutomation - INFO - Processing movie: 990140 (TMDB id)
2024-10-18 15:48:45,549 - ContentAutomation - INFO - Processing movie: 156022 (TMDB id)
2024-10-18 15:48:45,866 - ContentAutomation - INFO - Processing movie: 524434 (TMDB id)
2024-10-18 15:48:45,961 - ContentAutomation - INFO - Processing movie: 406759 (TMDB id)
2024-10-18 15:48:46,503 - ContentAutomation - INFO - Processing movie: 425909 (TMDB id)
[2024-10-18 15:48:46 +0800] [8] [CRITICAL] WORKER TIMEOUT (pid:9)
[2024-10-18 15:48:46 +0800] [9] [ERROR] Error handling request /run_now
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.13/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asgiref/sync.py", line 234, in __call__
    current_executor.run_until_future(loop_future)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 77, in run_until_future
    work_item = self._work_queue.get()
  File "/usr/local/lib/python3.13/queue.py", line 202, in get
    self.not_empty.wait()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/threading.py", line 359, in wait
    waiter.acquire()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
    sys.exit(1)
    ~~~~~~~~^^^
SystemExit: 1
[2024-10-18 15:48:46 +0800] [9] [INFO] Worker exiting (pid: 9)
2024-10-18 15:48:46,826 - ContentAutomation - INFO - Processing movie: 361743 (TMDB id)
2024-10-18 15:48:46,921 - ContentAutomation - INFO - Processing movie: 414906 (TMDB id)
2024-10-18 15:48:47,244 - ContentAutomation - INFO - Processing movie: 624860 (TMDB id)
2024-10-18 15:48:47,563 - ContentAutomation - INFO - Processing movie: 634649 (TMDB id)
[2024-10-18 15:48:47 +0800] [8] [ERROR] Worker (pid:9) was sent SIGKILL! Perhaps out of memory?
[2024-10-18 15:48:47 +0800] [54] [INFO] Booting worker with pid: 54
```

**Comment by giuseppe99barchetta** [comment] 2024-10-18 08:06
Hello! It looks like the issue may be related to a worker timeout or memory limitations. Could you provide some additional details to help me troubleshoot?

1. What environment are you running the Docker container on (e.g., hardware specifications, available memory, etc.)?
2. How many total TV shows and movies do you currently requested in Jellyseer?

With this information, I can better assist you in resolving the issue. Thanks!

**Comment by giuseppe99barchetta** [comment] 2024-10-18 08:27
Hi @trashken, could you please build and test the following Docker tag?

`ciuse99/suggestarr:test
`
Let me know if the issue is resolved or if you encounter any problems.

Thanks in advance!

**Closed** 2024-10-18 15:59 UTC
Labels: bug

**Comment by trashken** [comment] 2024-10-20 14:36
> Hi @trashken, could you please build and test the following Docker tag?
> 
> `ciuse99/suggestarr:test ` Let me know if the issue is resolved or if you encounter any problems.
> 
> Thanks in advance!

docker: Error response from daemon: manifest for ciuse99/suggestarr:test not found: manifest unknown: manifest unknown.

**Comment by trashken** [comment] 2024-10-20 14:37
> Hello! It looks like the issue may be related to a worker timeout or memory limitations. Could you provide some additional details to help me troubleshoot?
> 
> 1. What environment are you running the Docker container on (e.g., hardware specifications, available memory, etc.)?
> 2. How many total TV shows and movies do you currently requested in Jellyseer?
> 
> With this information, I can better assist you in resolving the issue. Thanks!

1. Running under Unraid 6.12.10. 16Gb RAM. 
2. 289 TV Shows

**Comment by giuseppe99barchetta** [comment] 2024-10-20 15:07
> > Hello! It looks like the issue may be related to a worker timeout or memory limitations. Could you provide some additional details to help me troubleshoot?
> 
> > 
> 
> > 1. What environment are you running the Docker container on (e.g., hardware specifications, available memory, etc.)?
> 
> > 2. How many total TV shows and movies do you currently requested in Jellyseer?
> 
> > 
> 
> > With this information, I can better assist you in resolving the issue. Thanks!
> 
> 
> 
> 1. Running under Unraid 6.12.10. 16Gb RAM. 
> 
> 2. 289 TV Shows

Hi! Should be solved in the latest tag.
