### ISSUE TITLE
[REQ] Selection for Folders

### ISSUE THREAD

**Issue by Xelator23** [giuseppe99barchetta/SuggestArr#65] opened 2024-10-27 12:00 UTC
Hi,

he will use all time the fis Normal and never the Anime for Anime's

![image](https://github.com/user-attachments/assets/28511ebc-2e85-4bac-b49e-b27dae308b64)

**Comment by giuseppe99barchetta** [comment] 2024-10-30 10:59
Duplicate of #55.

**Closed by giuseppe99barchetta** 2024-10-30 10:59 UTC
Labels: duplicate
